; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:d1_wroom_02]
platform = espressif32
board = esp32-c3-devkitm-1
board_build.mcu = esp32c3
upload_speed = 921600
framework = arduino
build_type = debug
lib_deps =
	ESP32Async/AsyncTCP@^3.4.7
	ESP32Async/ESPAsyncWebServer@^3.8.0
	arduino-libraries/Arduino_JSON@^0.2.0
#	ayushsharma82/ElegantOTA@^3.1.7
	adafruit/Adafruit NeoPixel@^1.12.5

monitor_filters = esp32_exception_decoder
build_flags = -DELEGANTOTA_USE_ASYNC_WEBSERVER=1
			  -D ARDUINO_USB_CDC_ON_BOOT=1
			  -D ARDUINO_USB_MODE=1
			  -DELEGANTOTA_DEBUG=1 -DDEBUG_ESP_SSL
			  -DDEBUG_ESP_TLS_MEM
			  -DDEBUG_ESP_HTTP_CLIENT
			  -DDEBUG_ESP_HTTP_SERVER
			  -DDEBUG_ESP_CORE
			  -DDEBUG_ESP_WIFI
			  -DDEBUG_ESP_HTTP_UPDATE
			  -DDEBUG_ESP_UPDATER
			  -DDEBUG_ESP_OTA
			  -DDEBUG_ESP_PORT=Serial
			  -DCORE_DEBUG_LEVEL=5
		#	  -DDEBUG_ESP_OOM -include "umm_malloc/umm_malloc_cfg.h"
			  -O2 -ggdb3 -g3 -std=gnu++17
build_unflags = -std=gnu++11



